version: '3'
services:
  coordinator:
    build: ./src/coordinator
    ports:
    - 4444:5432
    environment:
    - POSTGRESQL_USER=buddy
    - POSTGRESQL_PASSWORD=pw
    - POSTGRESQL_DATABASE=main
    - POSTGRESQL_ADMIN_PASSWORD=pw
    #volumes:
    #- ./src/coordinator/source_tracking_fdw/source_tracking_fdw.c:/usr/src/source_tracking_fdw/source_tracking_fdw.c
  contractor:
    build: ./src/contractor
    ports:
    - 4445-4455:5432 # specify port range for scaling multiple contractors
    environment:
    - POSTGRESQL_USER=buddy
    - POSTGRESQL_PASSWORD=pw
    - POSTGRESQL_DATABASE=main
    - POSTGRESQL_ADMIN_PASSWORD=pw
    volumes:
    - ./src/contractor/extend:/opt/app-root/src
    #- ./src/contractor/query_log/query_log.c:/usr/src/query_log/query_log.c
